package login

var authMenuSeedContracts = []menuSeed{
	{
		Key:       "login-log",
		ParentKey: "security",
		TitleKey:  "system.menu.loginLog",
		Path:      "/system/login-log",
		Component: "auth/LoginLogList",
		PagePerm:  "system:login-log:list",
		Type:      "C",
		Icon:      "clock",
		RouteName: "system-login-log",
		Module:    "system.auth",
		Sort:      10,
	},
	{
		Key:       "session",
		ParentKey: "security",
		TitleKey:  "system.menu.session",
		Path:      "/system/session",
		Component: "auth/SessionList",
		PagePerm:  "system:session:list",
		Type:      "C",
		Icon:      "desktop",
		RouteName: "system-session",
		Module:    "system.auth",
		Sort:      20,
	},
	{
		Key:       "security-event",
		ParentKey: "security",
		TitleKey:  "system.menu.securityEvent",
		Path:      "/system/security-event",
		Component: "auth/SecurityEventList",
		PagePerm:  "system:security-event:list",
		Type:      "C",
		Icon:      "safe",
		RouteName: "system-security-event",
		Module:    "system.auth",
		Sort:      30,
	},
	{Key: "login-log-export", ParentKey: "login-log", TitleKey: "system.permission.login_log.export", Perms: "system:login-log:export", Type: "F", Sort: 1},
	{Key: "login-log-clear", ParentKey: "login-log", TitleKey: "system.permission.login_log.clear", Perms: "system:login-log:clear", Type: "F", Sort: 2},
	{Key: "login-log-delete", ParentKey: "login-log", TitleKey: "system.permission.login_log.delete", Perms: "system:login-log:delete", Type: "F", Sort: 3},
	{Key: "session-delete", ParentKey: "session", TitleKey: "system.permission.session.delete", Perms: "system:session:delete", Type: "F", Sort: 1},
	{Key: "session-clear", ParentKey: "session", TitleKey: "system.permission.session.clear", Perms: "system:session:clear", Type: "F", Sort: 2},
	{Key: "security-event-acknowledge", ParentKey: "security-event", TitleKey: "system.permission.security_event.acknowledge", Perms: "system:security-event:acknowledge", Type: "F", Sort: 1},
}
