-- Pantheon Ops business schema. The base migration runner embeds and applies
-- this file in version order; business modules must not rely on AutoMigrate in
-- production mode.

CREATE TABLE IF NOT EXISTS `biz_business_scope` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `owner` VARCHAR(255) DEFAULT '',
  `environment` VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `dept_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `remark` TEXT,
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `deleted_at` DATETIME(3) DEFAULT NULL,
  `active_code` VARCHAR(255) GENERATED ALWAYS AS (IF(`deleted_at` IS NULL, `code`, NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_business_scope_code_active` (`active_code`),
  KEY `idx_business_scope_status` (`status`),
  KEY `idx_business_scope_dept_id` (`dept_id`),
  KEY `idx_business_scope_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_cmdb_host` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hostname` VARCHAR(128) NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `ssh_port` INT NOT NULL DEFAULT 22,
  `os` VARCHAR(32) NOT NULL,
  `os_version` VARCHAR(128) DEFAULT '',
  `cpu_cores` INT NOT NULL DEFAULT 0,
  `memory_gb` DOUBLE NOT NULL DEFAULT 0,
  `disk_gb` DOUBLE NOT NULL DEFAULT 0,
  `label_values` JSON,
  `installed_components` JSON,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `business_scope_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `business_scope_code` VARCHAR(64) DEFAULT '',
  `business_scope_name` VARCHAR(128) DEFAULT '',
  `dept_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `owner` VARCHAR(64) DEFAULT '',
  `remark` TEXT,
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `created_by` VARCHAR(64) DEFAULT '',
  `updated_by` VARCHAR(64) DEFAULT '',
  `deleted_at` DATETIME(3) DEFAULT NULL,
  `active_ip` VARCHAR(45) GENERATED ALWAYS AS (IF(`deleted_at` IS NULL, `ip`, NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cmdb_host_ip_active` (`active_ip`),
  KEY `idx_cmdb_host_status` (`status`),
  KEY `idx_cmdb_host_business_scope_id` (`business_scope_id`),
  KEY `idx_cmdb_host_dept_id` (`dept_id`),
  KEY `idx_cmdb_host_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_cmdb_group` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(128) NOT NULL,
  `conditions` JSON NOT NULL,
  `description` VARCHAR(512) DEFAULT '',
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cmdb_group_parent_id` (`parent_id`),
  KEY `idx_cmdb_group_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_cmdb_label_schema` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `category` VARCHAR(32) NOT NULL DEFAULT 'base',
  `value_mode` VARCHAR(16) NOT NULL DEFAULT 'free',
  `dict_code` VARCHAR(64) DEFAULT '',
  `options` JSON,
  `required` TINYINT(1) NOT NULL DEFAULT 0,
  `status` VARCHAR(16) NOT NULL DEFAULT 'enabled',
  `description` VARCHAR(512) DEFAULT '',
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `deleted_at` DATETIME(3) DEFAULT NULL,
  `active_key` VARCHAR(64) GENERATED ALWAYS AS (IF(`deleted_at` IS NULL, `key`, NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cmdb_label_schema_key_active` (`active_key`),
  KEY `idx_cmdb_label_schema_category` (`category`),
  KEY `idx_cmdb_label_schema_status` (`status`),
  KEY `idx_cmdb_label_schema_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_deploy_package` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `version` VARCHAR(64) NOT NULL,
  `description` VARCHAR(512) DEFAULT '',
  `install_command` TEXT,
  `uninstall_command` TEXT,
  `execution_mode` VARCHAR(32) NOT NULL DEFAULT 'fixed',
  `template_code` VARCHAR(64) DEFAULT '',
  `template_config` JSON,
  `source_object_key` VARCHAR(255) DEFAULT '',
  `source_file_name` VARCHAR(255) DEFAULT '',
  `source_url` VARCHAR(512) DEFAULT '',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `created_by` VARCHAR(64) DEFAULT '',
  `updated_by` VARCHAR(64) DEFAULT '',
  `deleted_at` DATETIME(3) DEFAULT NULL,
  `active_name_version` VARCHAR(255) GENERATED ALWAYS AS (IF(`deleted_at` IS NULL, CONCAT(`name`, '#', `version`), NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_deploy_package_name_version_active` (`active_name_version`),
  KEY `idx_deploy_package_execution_mode` (`execution_mode`),
  KEY `idx_deploy_package_template_code` (`template_code`),
  KEY `idx_deploy_package_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_deploy_template` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `version` VARCHAR(64) NOT NULL,
  `description` VARCHAR(512) DEFAULT '',
  `category` VARCHAR(64) DEFAULT '',
  `execution_mode` VARCHAR(32) NOT NULL DEFAULT 'fixed',
  `default_action` VARCHAR(32) NOT NULL DEFAULT 'install',
  `package_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `package_name` VARCHAR(128) DEFAULT '',
  `package_version` VARCHAR(64) DEFAULT '',
  `template_code` VARCHAR(64) DEFAULT '',
  `template_config` JSON,
  `parameter_schema` JSON,
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled',
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `created_by` VARCHAR(64) DEFAULT '',
  `updated_by` VARCHAR(64) DEFAULT '',
  `deleted_at` DATETIME(3) DEFAULT NULL,
  `active_name_version` VARCHAR(255) GENERATED ALWAYS AS (IF(`deleted_at` IS NULL, CONCAT(`name`, '#', `version`), NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_deploy_template_name_version_active` (`active_name_version`),
  KEY `idx_deploy_template_package_id` (`package_id`),
  KEY `idx_deploy_template_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_deploy_template_step` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `template_id` BIGINT UNSIGNED NOT NULL,
  `step_code` VARCHAR(64) NOT NULL,
  `step_name` VARCHAR(128) NOT NULL,
  `step_type` VARCHAR(32) NOT NULL,
  `action` VARCHAR(32) NOT NULL DEFAULT 'install',
  `package_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `package_name` VARCHAR(128) DEFAULT '',
  `package_version` VARCHAR(64) DEFAULT '',
  `template_code` VARCHAR(64) DEFAULT '',
  `template_params` JSON,
  `step_config` JSON,
  `sort` INT NOT NULL DEFAULT 1,
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_deploy_template_step_template_id` (`template_id`),
  KEY `idx_deploy_template_step_type` (`step_type`),
  KEY `idx_deploy_template_step_sort` (`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_deploy_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `template_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `template_name` VARCHAR(128) DEFAULT '',
  `template_version` VARCHAR(64) DEFAULT '',
  `package_id` BIGINT UNSIGNED NOT NULL,
  `package_name` VARCHAR(128) DEFAULT '',
  `package_version` VARCHAR(64) DEFAULT '',
  `business_scope_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `business_scope_name` VARCHAR(128) DEFAULT '',
  `action` VARCHAR(32) NOT NULL DEFAULT 'install',
  `target_type` VARCHAR(32) NOT NULL,
  `target_ids` JSON,
  `executor_type` VARCHAR(32) NOT NULL DEFAULT 'manual',
  `execution_mode` VARCHAR(32) NOT NULL DEFAULT 'fixed',
  `template_params` JSON,
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `remark` VARCHAR(512) DEFAULT '',
  `external_task_id` VARCHAR(128) DEFAULT '',
  `started_at` DATETIME(3) DEFAULT NULL,
  `finished_at` DATETIME(3) DEFAULT NULL,
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `created_by` VARCHAR(64) DEFAULT '',
  `updated_by` VARCHAR(64) DEFAULT '',
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_deploy_task_template_id` (`template_id`),
  KEY `idx_deploy_task_package_id` (`package_id`),
  KEY `idx_deploy_task_business_scope_id` (`business_scope_id`),
  KEY `idx_deploy_task_status` (`status`),
  KEY `idx_deploy_task_target_type` (`target_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_deploy_task_host` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `host_id` BIGINT UNSIGNED NOT NULL,
  `hostname` VARCHAR(128) DEFAULT '',
  `host_ip` VARCHAR(45) DEFAULT '',
  `os` VARCHAR(32) DEFAULT '',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `stdout` TEXT,
  `stderr` TEXT,
  `error_message` VARCHAR(512) DEFAULT '',
  `executor_id` VARCHAR(128) DEFAULT '',
  `trace_steps` JSON,
  `started_at` DATETIME(3) DEFAULT NULL,
  `finished_at` DATETIME(3) DEFAULT NULL,
  `reported_at` DATETIME(3) DEFAULT NULL,
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `updated_by` VARCHAR(64) DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_deploy_task_host` (`task_id`, `host_id`),
  KEY `idx_deploy_task_host_task_id` (`task_id`),
  KEY `idx_deploy_task_host_host_id` (`host_id`),
  KEY `idx_deploy_task_host_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_k8s_cluster` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(128) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `environment` VARCHAR(50) NOT NULL,
  `business_scope_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `business_scope_name` VARCHAR(255) DEFAULT '',
  `dept_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `api_server` VARCHAR(512) DEFAULT '',
  `kubeconfig_encrypted` TEXT,
  `version` VARCHAR(64) DEFAULT '',
  `status` VARCHAR(50) NOT NULL DEFAULT 'unknown',
  `total_nodes` INT NOT NULL DEFAULT 0,
  `ready_nodes` INT NOT NULL DEFAULT 0,
  `total_pods` INT NOT NULL DEFAULT 0,
  `running_pods` INT NOT NULL DEFAULT 0,
  `cpu_capacity` DOUBLE NOT NULL DEFAULT 0,
  `cpu_allocatable` DOUBLE NOT NULL DEFAULT 0,
  `memory_capacity` DOUBLE NOT NULL DEFAULT 0,
  `memory_allocatable` DOUBLE NOT NULL DEFAULT 0,
  `last_synced_at` DATETIME(3) DEFAULT NULL,
  `remark` TEXT,
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `created_by` VARCHAR(64) DEFAULT '',
  `updated_by` VARCHAR(64) DEFAULT '',
  `deleted_at` DATETIME(3) DEFAULT NULL,
  `active_code` VARCHAR(128) GENERATED ALWAYS AS (IF(`deleted_at` IS NULL, `code`, NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_k8s_cluster_code_active` (`active_code`),
  KEY `idx_k8s_cluster_business_scope_id` (`business_scope_id`),
  KEY `idx_k8s_cluster_environment` (`environment`),
  KEY `idx_k8s_cluster_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `biz_k8s_release` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cluster_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `namespace` VARCHAR(255) NOT NULL,
  `business_scope_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `dept_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `workload_type` VARCHAR(50) NOT NULL,
  `workload_name` VARCHAR(255) NOT NULL,
  `container_name` VARCHAR(255) DEFAULT '',
  `image_before` VARCHAR(512) DEFAULT '',
  `image_after` VARCHAR(512) NOT NULL,
  `strategy` VARCHAR(50) NOT NULL DEFAULT 'RollingUpdate',
  `status` VARCHAR(50) NOT NULL DEFAULT 'pending',
  `error_message` TEXT,
  `started_at` DATETIME(3) DEFAULT NULL,
  `finished_at` DATETIME(3) DEFAULT NULL,
  `created_by` VARCHAR(64) DEFAULT '',
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_k8s_release_cluster_id` (`cluster_id`),
  KEY `idx_k8s_release_business_scope_id` (`business_scope_id`),
  KEY `idx_k8s_release_status` (`status`),
  KEY `idx_k8s_release_workload` (`workload_type`, `workload_name`),
  KEY `idx_k8s_release_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
