import { defineModule } from '../../../core/router/types';

export const K8sModule = defineModule({
  name: 'k8s',
  scope: 'business',
  routes: [
    {
      path: 'business/k8s/cluster',
      routeName: 'k8s-cluster-list',
      titleKey: 'operations.k8s.cluster.menu',
      icon: 'apps',
      pagePermission: 'business:k8s:cluster:list',
      componentKey: 'business/k8s/cluster/ClusterList',
    },
    {
      path: 'business/k8s/cluster/:id',
      routeName: 'k8s-cluster-detail',
      titleKey: 'business.k8s.cluster.detail',
      pagePermission: 'business:k8s:cluster:view',
      activeMenu: '/business/k8s/cluster',
      componentKey: 'business/k8s/cluster/ClusterDetail',
    },
    {
      path: 'business/k8s/workload',
      routeName: 'k8s-workload-list',
      titleKey: 'operations.k8s.workload.menu',
      icon: 'storage',
      pagePermission: 'business:k8s:workload:list',
      componentKey: 'business/k8s/workload/WorkloadList',
    },
    {
      path: 'business/k8s/release',
      routeName: 'k8s-release-list',
      titleKey: 'operations.k8s.release.menu',
      icon: 'code',
      pagePermission: 'business:k8s:release:list',
      componentKey: 'business/k8s/release/ReleaseList',
    },
  ],
  menus: [
    {
      path: '/business/k8s/cluster',
      titleKey: 'operations.k8s.cluster.menu',
      icon: 'apps',
      routeName: 'k8s-cluster-list',
      module: 'business.k8s',
    },
    {
      path: '/business/k8s/workload',
      titleKey: 'operations.k8s.workload.menu',
      icon: 'storage',
      routeName: 'k8s-workload-list',
      module: 'business.k8s',
    },
    {
      path: '/business/k8s/release',
      titleKey: 'operations.k8s.release.menu',
      icon: 'code',
      routeName: 'k8s-release-list',
      module: 'business.k8s',
    },
  ],
  permissions: [
    'business:k8s:cluster:list',
    'business:k8s:cluster:view',
    'business:k8s:cluster:create',
    'business:k8s:cluster:update',
    'business:k8s:cluster:delete',
    'business:k8s:workload:list',
    'business:k8s:workload:view',
    'business:k8s:workload:update',
    'business:k8s:release:list',
    'business:k8s:release:view',
    'business:k8s:release:create',
    'business:k8s:release:rollback',
    'business:k8s:release:reconcile',
  ],
  i18nNamespaces: ['business.k8s'],
});
