import { defineModule } from '../../../core/router/types';

export const ObservabilityModule = defineModule({
  name: 'observability',
  scope: 'business',
  routes: [
    {
      path: 'business/observability/metrics/sources',
      routeName: 'observability-metric-sources',
      titleKey: 'operations.observability.metrics.sources.menu',
      icon: 'code-block',
      pagePermission: 'business:observability:metric_source:view',
      componentKey: 'business/observability/MetricSourceList',
    },
    {
      path: 'business/observability/alerts/rules',
      routeName: 'observability-alert-rules',
      titleKey: 'operations.observability.alerts.rules.menu',
      icon: 'notification',
      pagePermission: 'business:observability:alert_rule:view',
      componentKey: 'business/observability/AlertRuleList',
    },
    {
      path: 'business/observability/alerts/records',
      routeName: 'observability-alert-records',
      titleKey: 'operations.observability.alerts.records.menu',
      icon: 'history',
      pagePermission: 'business:observability:alert_record:view',
      componentKey: 'business/observability/AlertRecordList',
    },
    {
      path: 'business/observability/alerts/active',
      routeName: 'observability-active-alerts',
      titleKey: 'operations.observability.alerts.active.menu',
      icon: 'exclamation-circle',
      pagePermission: 'business:observability:alert_record:view',
      componentKey: 'business/observability/ActiveAlertList',
    },
    {
      path: 'business/observability/alerts/channels',
      routeName: 'observability-notification-channels',
      titleKey: 'operations.observability.alerts.channels.menu',
      icon: 'send',
      pagePermission: 'business:observability:notification_channel:view',
      componentKey: 'business/observability/NotificationChannelList',
    },
  ],
  menus: [
    {
      path: '/business/observability',
      titleKey: 'operations.observability.menu',
      icon: 'eye',
      routeName: 'observability',
      module: 'business.observability',
      children: [
        {
          path: '/business/observability/metrics/sources',
          titleKey: 'operations.observability.metrics.sources.menu',
          icon: 'code-block',
          routeName: 'observability-metric-sources',
          module: 'business.observability',
        },
        {
          path: '/business/observability/alerts/rules',
          titleKey: 'operations.observability.alerts.rules.menu',
          icon: 'notification',
          routeName: 'observability-alert-rules',
          module: 'business.observability',
        },
        {
          path: '/business/observability/alerts/active',
          titleKey: 'operations.observability.alerts.active.menu',
          icon: 'exclamation-circle',
          routeName: 'observability-active-alerts',
          module: 'business.observability',
        },
        {
          path: '/business/observability/alerts/records',
          titleKey: 'operations.observability.alerts.records.menu',
          icon: 'history',
          routeName: 'observability-alert-records',
          module: 'business.observability',
        },
        {
          path: '/business/observability/alerts/channels',
          titleKey: 'operations.observability.alerts.channels.menu',
          icon: 'send',
          routeName: 'observability-notification-channels',
          module: 'business.observability',
        },
      ],
    },
  ],
  permissions: [
    'business:observability:metric_source:view',
    'business:observability:metric_source:create',
    'business:observability:metric_source:update',
    'business:observability:metric_source:delete',
    'business:observability:alert_rule:view',
    'business:observability:alert_rule:create',
    'business:observability:alert_rule:update',
    'business:observability:alert_rule:delete',
    'business:observability:alert_record:view',
    'business:observability:notification_channel:view',
    'business:observability:notification_channel:create',
    'business:observability:notification_channel:update',
    'business:observability:notification_channel:delete',
  ],
  i18nNamespaces: ['business.observability'],
});
